# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("newborn", "0001_initial"),
        ("organisations", "0001_initial"),
        ("pregnancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("referral_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REQUESTED", "Requested"),
                            (
                                "RECEIVING_FACILITY_NOTIFIED",
                                "Receiving Facility Notified",
                            ),
                            ("ACCEPTED", "Accepted"),
                            ("TRANSPORT_REQUESTED", "Transport Requested"),
                            ("IN_TRANSIT", "In Transit"),
                            ("ARRIVED", "Arrived"),
                            ("DISPOSITION_RECORDED", "Disposition Recorded"),
                            ("CLOSED", "Closed"),
                            ("DECLINED", "Declined"),
                            ("NO_ACK_ESCALATED", "No Ack — Escalated"),
                            ("TRANSPORT_UNAVAILABLE", "Transport Unavailable"),
                            ("CANCELLED_BY_CLINICIAN", "Cancelled by Clinician"),
                            ("LOST_TO_FOLLOWUP", "Lost to Follow-up"),
                        ],
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("PRIORITY", "Priority Review"),
                            ("ROUTINE", "Routine"),
                            ("ABSTAIN", "Abstain — Insufficient Data"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("pre_referral_care", models.TextField(blank=True)),
                ("qr_token", models.CharField(blank=True, max_length=200)),
                ("short_code", models.CharField(blank=True, max_length=20)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("disposition", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                (
                    "destination_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_referrals",
                        to="organisations.organisationunit",
                    ),
                ),
                (
                    "newborn_episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="newborn.newbornepisode",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="clients.person",
                    ),
                ),
                (
                    "pregnancy_episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pregnancy.pregnancyepisode",
                    ),
                ),
                (
                    "referring_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_referrals",
                        to="organisations.organisationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralStateLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=40)),
                ("to_status", models.CharField(max_length=40)),
                ("actor", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_logs",
                        to="referrals.referral",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
