# Generated by Django 5.1.5 on 2026-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="estimated_transport_time_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referral",
            name="in_transit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referral",
            name="transport_mode",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="referral",
            name="transport_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
