# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "notification_class",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("REFERRAL", "Referral"),
                            ("APPOINTMENT", "Appointment"),
                            ("DEFAULTER", "Defaulter"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ACTED", "Acted Upon"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("PRIORITY", "Priority Review"),
                            ("ROUTINE", "Routine"),
                            ("ABSTAIN", "Abstain — Insufficient Data"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("due_datetime", models.DateTimeField(blank=True, null=True)),
                ("related_entity_type", models.CharField(blank=True, max_length=50)),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("recorded_by", models.CharField(blank=True, max_length=200)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
