# Generated by Django 5.1.5 on 2026-08-07 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("request_method", models.CharField(max_length=10)),
                ("request_path", models.CharField(max_length=255)),
                ("request_body_hash", models.CharField(blank=True, max_length=64)),
                ("response_status", models.IntegerField()),
                ("response_body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="core_idempo_key_b2286d_idx"),
                    models.Index(
                        fields=["user", "key"], name="core_idempo_user_id_ffde72_idx"
                    ),
                ],
            },
        ),
    ]
