# Generated by Django 5.1.5 on 2026-08-07 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_idempotency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clinical_ml_mode",
                    models.CharField(
                        choices=[
                            ("RULES_ONLY", "Rules Only"),
                            ("SILENT", "Silent"),
                            ("ASSISTED", "Assisted"),
                        ],
                        default="RULES_ONLY",
                        max_length=20,
                    ),
                ),
                ("engagement_model_enabled", models.BooleanField(default=False)),
                ("ocr_enabled", models.BooleanField(default=True)),
                ("ivr_dtmf_enabled", models.BooleanField(default=True)),
                ("ussd_enabled", models.BooleanField(default=True)),
                ("speech_capture_enabled", models.BooleanField(default=False)),
                ("remote_emergency_cascade_enabled", models.BooleanField(default=True)),
                ("print_referral_slip_enabled", models.BooleanField(default=True)),
                ("sync_batch_size", models.PositiveIntegerField(default=100)),
                ("sync_retry_max", models.PositiveIntegerField(default=5)),
                (
                    "sync_retry_backoff_base_seconds",
                    models.PositiveIntegerField(default=30),
                ),
                (
                    "referral_ack_timeout_minutes",
                    models.PositiveIntegerField(default=30),
                ),
                (
                    "referral_escalation_timeout_minutes",
                    models.PositiveIntegerField(default=60),
                ),
                (
                    "scan_retention_mode",
                    models.CharField(default="TEMPORARY_WORKING_COPY", max_length=30),
                ),
                (
                    "scan_temporary_retention_hours",
                    models.PositiveIntegerField(default=24),
                ),
                (
                    "active_rule_bundle_version",
                    models.CharField(default="ghs-smp-2016-v1", max_length=50),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
    ]
