# Generated by Django 5.1.5 on 2026-08-07 22:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_system_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "package_id",
                    models.CharField(max_length=200, verbose_name="Package ID"),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL_RULES", "Clinical Rule Bundle"),
                            ("CLINICAL_ML_MODEL", "Clinical ML Model"),
                            ("ENGAGEMENT_MODEL", "Engagement Model"),
                            ("OCR_MODEL", "OCR Model"),
                            ("MCH_TEMPLATE", "MCH Template Definition"),
                            ("TELEPHONY_PROMPT", "Telephony Prompt Pack"),
                            (
                                "REFERRAL_DIRECTORY",
                                "Referral Capability/Contact Directory",
                            ),
                            ("APP_CONFIG", "Application Configuration"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(max_length=50, verbose_name="Semver Version"),
                ),
                (
                    "created_at_pkg",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("minimum_app_version", models.CharField(blank=True, max_length=50)),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="SHA-256 Hash"),
                ),
                (
                    "signature",
                    models.TextField(blank=True, verbose_name="Package Signature"),
                ),
                ("signing_key_id", models.CharField(blank=True, max_length=100)),
                ("previous_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STAGED", "Staged"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="STAGED",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["package_type", "status"],
                        name="core_packag_package_1aba25_idx",
                    ),
                    models.Index(
                        fields=["package_id", "version"],
                        name="core_packag_package_ced7e8_idx",
                    ),
                ],
            },
        ),
    ]
