# Generated by Django 5.1.5 on 2026-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_telephony_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="ocr_confidence_thresholds",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="referral_destinations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="role_contact_numbers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="supported_mch_template_versions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
