# Generated by Django 5.1.5 on 2026-08-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_systemconfig_ocr_confidence_thresholds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending — image uploaded, not yet processed"),
                    ("PROCESSING", "Processing — OCR in progress"),
                    (
                        "EXTRACTED",
                        "Extracted — fields extracted, awaiting confirmation",
                    ),
                    (
                        "CONFIRMED",
                        "Confirmed — human confirmed, ready for clinical use",
                    ),
                    ("REJECTED", "Rejected — human rejected the extraction"),
                    ("FAILED", "Failed — OCR processing error"),
                    (
                        "UNKNOWN_TEMPLATE",
                        "Unknown template — manual entry required (spec §16.4)",
                    ),
                    ("EXPIRED", "Expired — retention window elapsed, image purged"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
