# Generated by Django 5.1.5 on 2026-08-09 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_template_fields"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role key, e.g. MIDWIFE, CHO, FACILITY_ADMIN",
                        max_length=50,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility this contact belongs to. Null = system-wide.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisationunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Contact",
                "verbose_name_plural": "Role Contacts",
                "ordering": ["facility", "role"],
                "unique_together": {("facility", "role")},
            },
        ),
    ]
