# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowthMeasurement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("measurement_date", models.DateField()),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("measurement_position", models.CharField(blank=True, max_length=20)),
                (
                    "muac_mm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="MUAC (mm)"
                    ),
                ),
                ("feeding_status", models.CharField(blank=True, max_length=50)),
                ("recent_illness", models.CharField(blank=True, max_length=200)),
                ("measurement_quality", models.CharField(blank=True, max_length=50)),
                ("scale_id", models.CharField(blank=True, max_length=50)),
                ("length_board_id", models.CharField(blank=True, max_length=50)),
                ("indicator", models.CharField(default="NORMAL", max_length=30)),
                ("recorded_by", models.CharField(blank=True, max_length=200)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_measurements",
                        to="clients.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-measurement_date"],
            },
        ),
    ]
