# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganisationUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("REGION", "Region"),
                            ("DISTRICT", "District"),
                            ("SUBDISTRICT", "Sub-district"),
                            ("FACILITY", "Facility"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHPS", "CHPS"),
                            ("HEALTH_CENTRE", "Health Centre"),
                            ("DISTRICT_HOSPITAL", "District Hospital"),
                            ("REGIONAL_HOSPITAL", "Regional Hospital"),
                            ("TEACHING_HOSPITAL", "Teaching Hospital"),
                            ("CLINIC", "Clinic"),
                            ("MATERNITY_HOME", "Maternity Home"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organisations.organisationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["unit_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="FacilityCapability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("maternity_triage_24_7", models.BooleanField(default=False)),
                (
                    "bemonc",
                    models.BooleanField(
                        default=False, help_text="Basic Emergency Obstetric Care"
                    ),
                ),
                (
                    "cemonc",
                    models.BooleanField(
                        default=False,
                        help_text="Comprehensive Emergency Obstetric Care",
                    ),
                ),
                ("theatre", models.BooleanField(default=False)),
                ("blood", models.BooleanField(default=False)),
                ("specialist_obstetrics", models.BooleanField(default=False)),
                ("newborn_support", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "backup_referral_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_referrals_from",
                        to="organisations.organisationunit",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        limit_choices_to={"unit_type": "FACILITY"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capabilities",
                        to="organisations.organisationunit",
                    ),
                ),
                (
                    "primary_referral_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_referrals_from",
                        to="organisations.organisationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["facility__name"],
            },
        ),
    ]
