# Generated by Django 5.1.5 on 2026-08-07 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor", models.CharField(max_length=200)),
                ("actor_role", models.CharField(blank=True, max_length=50)),
                ("action", models.CharField(max_length=100)),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                ("patient_id", models.UUIDField(blank=True, null=True)),
                ("facility_id", models.UUIDField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=100)),
                ("purpose", models.CharField(default="DIRECT_CARE", max_length=50)),
                ("metadata", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
