# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PregnancyEpisode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("assigned_chps", models.CharField(blank=True, max_length=200)),
                ("assigned_worker", models.CharField(blank=True, max_length=200)),
                (
                    "lmp_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Menstrual Period"
                    ),
                ),
                (
                    "lmp_reliability",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No"), ("UNKNOWN", "Unknown")],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("dating_method", models.CharField(blank=True, max_length=50)),
                ("gravidity", models.PositiveIntegerField(default=0)),
                ("parity", models.PositiveIntegerField(default=0)),
                ("living_children", models.PositiveIntegerField(default=0)),
                ("previous_caesarean_count", models.PositiveIntegerField(default=0)),
                ("previous_uterine_surgery", models.BooleanField(default=False)),
                ("previous_stillbirth", models.BooleanField(default=False)),
                ("previous_neonatal_death", models.BooleanField(default=False)),
                (
                    "previous_pph",
                    models.BooleanField(default=False, verbose_name="Previous PPH"),
                ),
                ("previous_preeclampsia_eclampsia", models.BooleanField(default=False)),
                ("previous_preterm_birth", models.BooleanField(default=False)),
                ("previous_obstructed_labour", models.BooleanField(default=False)),
                (
                    "maternal_age_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("height_cm", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "booking_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("chronic_hypertension", models.BooleanField(default=False)),
                ("diabetes", models.BooleanField(default=False)),
                ("sickle_cell_status", models.CharField(blank=True, max_length=30)),
                ("cardiac_disease", models.BooleanField(default=False)),
                ("renal_disease", models.BooleanField(default=False)),
                ("epilepsy", models.BooleanField(default=False)),
                ("blood_group", models.CharField(blank=True, max_length=10)),
                ("rhesus_status", models.CharField(blank=True, max_length=10)),
                (
                    "travel_time_referral_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("birth_plan_complete", models.BooleanField(default=False)),
                ("hiv_status", models.CharField(blank=True, max_length=20)),
                ("syphilis_status", models.CharField(blank=True, max_length=20)),
                ("hepatitis_b_status", models.CharField(blank=True, max_length=20)),
                ("tb_status", models.CharField(blank=True, max_length=20)),
                ("late_booking_or_missed_anc", models.BooleanField(default=False)),
                ("severe_access_barrier", models.BooleanField(default=False)),
                (
                    "specialist_recommendation_incomplete",
                    models.BooleanField(default=False),
                ),
                (
                    "current_urgency",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("PRIORITY", "Priority Review"),
                            ("ROUTINE", "Routine"),
                            ("ABSTAIN", "Abstain — Insufficient Data"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason", models.TextField(blank=True)),
                (
                    "woman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregnancies",
                        to="clients.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PregnancyAssessment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("PRIORITY", "Priority Review"),
                            ("ROUTINE", "Routine"),
                            ("ABSTAIN", "Abstain — Insufficient Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fired_rules", models.JSONField(default=list)),
                ("recommended_action", models.TextField(blank=True)),
                (
                    "rule_set_version",
                    models.CharField(default="placeholder-v0", max_length=50),
                ),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="pregnancy.pregnancyepisode",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessed_at"],
            },
        ),
        migrations.CreateModel(
            name="PregnancyObservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recorded_by", models.CharField(blank=True, max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("bp_systolic", models.PositiveIntegerField(blank=True, null=True)),
                ("bp_diastolic", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fundal_height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "fhr_bpm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fetal Heart Rate"
                    ),
                ),
                ("urine_protein", models.CharField(blank=True, max_length=20)),
                ("urine_glucose", models.CharField(blank=True, max_length=20)),
                ("oedema", models.CharField(blank=True, max_length=20)),
                ("movement_status", models.CharField(blank=True, max_length=50)),
                ("danger_signs", models.TextField(blank=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="pregnancy.pregnancyepisode",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
