# Generated by Django 5.1.5 on 2026-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pregnancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregnancyepisode",
            name="average_daily_working_hours",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="pregnancyepisode",
            name="maternal_education",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pregnancyepisode",
            name="maternal_occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pregnancyepisode",
            name="number_of_jobs",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="anaemia_symptoms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="bp_repeat_after_rest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="capture_route",
            field=models.CharField(default="MANUAL", max_length=20),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="captured_by",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="client_uncontactable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="contractions",
            field=models.CharField(blank=True, default="NONE", max_length=20),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="convulsion_or_unconsciousness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="correction_of_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="correction_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="definitive_fetal_assessment_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="device_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="emergency_referral_incomplete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="epigastric_pain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="fetal_heart_seriously_abnormal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="fetal_number",
            field=models.CharField(blank=True, default="SINGLE", max_length=20),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="fever_or_severe_illness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="fhr_repeat_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="fluid_leakage",
            field=models.CharField(blank=True, default="NONE", max_length=20),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="growth_trend_static",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="hb_g_dl",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Haemoglobin",
            ),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="hb_required_by_protocol",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="human_confirmed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="jaundice_or_liver_symptoms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="ocr_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="offensive_discharge_with_fever_pain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="persistent_vomiting_dehydration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="presentation",
            field=models.CharField(blank=True, default="UNKNOWN", max_length=20),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="records_conflicting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="respiratory_rate_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="severe_abdominal_pain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="severe_anaemia_symptoms_unstable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="severe_breathing_difficulty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="severe_headache",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="source_artifact_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="suspected_cord_prolapse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="suspected_sepsis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="suspected_shock_or_collapse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="symptom_not_understood",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="template_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="urgent_referral_incomplete_stable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="uterine_size_discrepancy_weeks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="vaginal_bleeding",
            field=models.CharField(blank=True, default="NONE", max_length=20),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="visual_disturbance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="worker_judgement_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pregnancyobservation",
            name="worker_judgement_rationale",
            field=models.TextField(blank=True),
        ),
    ]
