# Generated by Django 5.1.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_mfa_factor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="can_view_reports",
        ),
    ]
