# Generated by Django 5.1.5 on 2026-08-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_device_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="oidc_sub",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
