# Generated by Django 5.1.5 on 2026-08-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_useraccount_oidc_sub"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="oidc_sub",
        ),
    ]
