# Generated by Django 5.1.5 on 2026-08-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_oidc_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="fcm_token",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="FCM Token"
            ),
        ),
    ]
