# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("household_name", models.CharField(max_length=200)),
                ("head_person_name", models.CharField(blank=True, max_length=200)),
                ("location_description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "organisation_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="households",
                        to="organisations.organisationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["household_name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("national_id", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("community", models.CharField(blank=True, max_length=200)),
                ("landmark", models.TextField(blank=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("dag", "Dagbani"),
                            ("gjn", "Gonja"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("sensitive_content_consent", models.BooleanField(default=True)),
                ("communication_opt_out", models.BooleanField(default=False)),
                ("deceased", models.BooleanField(default=False)),
                ("deceased_verified", models.BooleanField(default=False)),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="clients.household",
                    ),
                ),
                (
                    "organisation_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="organisations.organisationunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaregiverLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relationship", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="clients.person",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_links",
                        to="clients.person",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "caregiver")},
            },
        ),
    ]
