# Generated by Django 5.1.5 on 2026-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="care_consent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="ivr_contact_consent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="model_training_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="research_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="research_waiver_status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="person",
            name="safe_calling_times",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="person",
            name="shared_phone_status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="person",
            name="ussd_contact_consent",
            field=models.BooleanField(default=True),
        ),
    ]
