# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("valid_records", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("DHIS2", "DHIS2"),
                            ("FHIR", "FHIR Server"),
                            ("TELEPHONY", "Telephony Gateway"),
                            ("SMS_GATEWAY", "SMS Gateway"),
                            ("OIDC", "OIDC Provider"),
                        ],
                        max_length=30,
                    ),
                ),
                ("provider_name", models.CharField(max_length=200)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("base_url", models.URLField(blank=True)),
                (
                    "api_key_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference to secret, not the key itself",
                        max_length=200,
                    ),
                ),
                ("config_data", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("person_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(default="COMMITTED", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="integrations.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
    ]
