# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("pregnancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthEpisode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("birth_datetime", models.DateTimeField(blank=True, null=True)),
                ("facility", models.CharField(blank=True, max_length=200)),
                ("birth_location", models.CharField(blank=True, max_length=100)),
                ("delivery_type", models.CharField(blank=True, max_length=50)),
                (
                    "labour_duration_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("complications", models.TextField(blank=True)),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="births",
                        to="clients.person",
                    ),
                ),
                (
                    "pregnancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pregnancy.pregnancyepisode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewbornEpisode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("TRANSFERRED", "Transferred"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("assigned_chps", models.CharField(blank=True, max_length=200)),
                ("assigned_worker", models.CharField(blank=True, max_length=200)),
                (
                    "multiple_birth_order",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "gestational_age_weeks",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("birth_weight_g", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "head_circumference_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("cried_or_breathed_immediately", models.BooleanField(default=True)),
                ("resuscitation_required", models.BooleanField(default=False)),
                (
                    "resuscitation_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("apgar_1_min", models.PositiveIntegerField(blank=True, null=True)),
                ("apgar_5_min", models.PositiveIntegerField(blank=True, null=True)),
                ("essential_care_complete", models.BooleanField(default=False)),
                (
                    "breastfeeding_initiation_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("kmc_status", models.CharField(blank=True, max_length=30)),
                ("kmc_hours_24h", models.PositiveIntegerField(blank=True, null=True)),
                ("hospital_discharge_date", models.DateField(blank=True, null=True)),
                ("discharge_diagnoses", models.TextField(blank=True)),
                (
                    "next_follow_up_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "travel_time_referral_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "current_location_status",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "maternal_ability_to_care",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No"), ("UNKNOWN", "Unknown")],
                        default="UNKNOWN",
                        max_length=30,
                    ),
                ),
                ("alternative_caregiver_available", models.BooleanField(default=False)),
                ("previous_newborn_unit_admission", models.BooleanField(default=False)),
                ("congenital_abnormality", models.BooleanField(default=False)),
                ("complex_feeding_plan", models.BooleanField(default=False)),
                ("maternal_death", models.BooleanField(default=False)),
                ("severe_access_barrier", models.BooleanField(default=False)),
                ("missed_postnatal_contact", models.BooleanField(default=False)),
                (
                    "current_urgency",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("PRIORITY", "Priority Review"),
                            ("ROUTINE", "Routine"),
                            ("ABSTAIN", "Abstain — Insufficient Data"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "birth_episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="newborn.birthepisode",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newborn_episodes",
                        to="clients.person",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newborns",
                        to="clients.person",
                    ),
                ),
                (
                    "pregnancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pregnancy.pregnancyepisode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewbornAssessment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("PRIORITY", "Priority Review"),
                            ("ROUTINE", "Routine"),
                            ("ABSTAIN", "Abstain — Insufficient Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fired_rules", models.JSONField(default=list)),
                ("recommended_action", models.TextField(blank=True)),
                (
                    "rule_set_version",
                    models.CharField(default="placeholder-v0", max_length=50),
                ),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="newborn.newbornepisode",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessed_at"],
            },
        ),
        migrations.CreateModel(
            name="NewbornObservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recorded_by", models.CharField(blank=True, max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "respiratory_rate_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("severe_chest_indrawing", models.BooleanField(default=False)),
                ("convulsions", models.BooleanField(default=False)),
                ("feeding_status", models.CharField(blank=True, max_length=50)),
                ("movement_status", models.CharField(blank=True, max_length=50)),
                ("grunting", models.BooleanField(default=False)),
                ("apnoea_or_gasping", models.BooleanField(default=False)),
                ("central_cyanosis", models.BooleanField(default=False)),
                ("bulging_fontanelle", models.BooleanField(default=False)),
                ("abdominal_distension", models.BooleanField(default=False)),
                ("yellow_palms_soles", models.BooleanField(default=False)),
                ("suck_quality", models.CharField(blank=True, max_length=50)),
                ("feeds_last_24h", models.CharField(blank=True, max_length=50)),
                ("vomiting", models.CharField(blank=True, max_length=50)),
                (
                    "jaundice_onset_age_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "bilirubin_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("umbilical_status", models.CharField(blank=True, max_length=50)),
                ("skin_pustules_extent", models.CharField(blank=True, max_length=50)),
                ("eye_discharge", models.CharField(blank=True, max_length=50)),
                ("urine_passed", models.CharField(blank=True, max_length=20)),
                ("meconium_passed", models.CharField(blank=True, max_length=20)),
                (
                    "current_weight_g",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("worker_judgement_critical", models.BooleanField(default=False)),
                ("worker_judgement_rationale", models.TextField(blank=True)),
                (
                    "newborn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="newborn.newbornepisode",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
