# Generated by Django 5.1.5 on 2026-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newborn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthepisode",
            name="liquor_quality",
            field=models.CharField(blank=True, default="CLEAR", max_length=30),
        ),
        migrations.AddField(
            model_name="birthepisode",
            name="maternal_fever_labour",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="birthepisode",
            name="mode_of_delivery",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="birthepisode",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="birthepisode",
            name="rupture_membranes_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="birthepisode",
            name="skilled_attendant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="capture_route",
            field=models.CharField(default="MANUAL", max_length=20),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="captured_by",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="caregiver_uncontactable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="correction_of_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="correction_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="device_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="discharged_sick_small",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="human_confirmed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="is_danger_assessment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="is_required_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="marked_illness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="missed_early_followup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="newborn_exam_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="ocr_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="recurrent_hypothermia_despite_warming",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="respiratory_abnormality_needs_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="rr_repeat_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="source_artifact_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="suspected_severe_infection",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="symptom_not_understood",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newbornobservation",
            name="template_version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
