# Generated by Django 5.1.5 on 2026-08-07 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ANC_COVERAGE", "ANC Coverage"),
                            ("REFERRAL_OUTCOMES", "Referral Outcomes"),
                            ("IMMUNISATION_COVERAGE", "Immunisation Coverage"),
                            ("GROWTH_SUMMARY", "Growth Summary"),
                            ("DEFAULTER_ANALYSIS", "Defaulter Analysis"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("data_snapshot", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ANC_COVERAGE", "ANC Coverage"),
                            ("REFERRAL_OUTCOMES", "Referral Outcomes"),
                            ("IMMUNISATION_COVERAGE", "Immunisation Coverage"),
                            ("GROWTH_SUMMARY", "Growth Summary"),
                            ("DEFAULTER_ANALYSIS", "Defaulter Analysis"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("frequency", models.CharField(default="MONTHLY", max_length=20)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
