# Generated by Django 5.1.5 on 2026-08-07 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CWCSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facility_name", models.CharField(max_length=200)),
                ("session_date", models.DateField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Session"),
                            ("OUTREACH", "Outreach"),
                            ("MOBILE", "Mobile"),
                        ],
                        default="FIXED",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("expected_count", models.PositiveIntegerField(default=0)),
                ("attended_count", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="ChildImmunisationRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("cwc_card_number", models.CharField(blank=True, max_length=50)),
                ("residence_status", models.CharField(blank=True, max_length=30)),
                ("current_chps", models.CharField(blank=True, max_length=200)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "defaulter_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRACED", "Traced"),
                            ("RESOLVED", "Resolved"),
                            ("LOST", "Lost to Follow-up"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("overdue_count", models.PositiveIntegerField(default=0)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunisation_records",
                        to="clients.person",
                    ),
                ),
                (
                    "primary_caregiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="immunisation_dependents",
                        to="clients.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DefaulterEpisode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("child_name", models.CharField(blank=True, max_length=200)),
                (
                    "defaulter_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRACED", "Traced"),
                            ("RESOLVED", "Resolved"),
                            ("LOST", "Lost to Follow-up"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("days_overdue", models.PositiveIntegerField(default=0)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "trace_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("CONTACTED", "Contacted"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("traced_at", models.DateTimeField(blank=True, null=True)),
                ("trace_notes", models.TextField(blank=True)),
                (
                    "child_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defaulter_episodes",
                        to="immunisation.childimmunisationrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VaccineDose",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vaccine_code", models.CharField(max_length=50)),
                ("vaccine_name", models.CharField(blank=True, max_length=100)),
                ("dose_number", models.PositiveIntegerField()),
                ("administration_date", models.DateField()),
                ("batch_lot", models.CharField(blank=True, max_length=50)),
                ("product_name", models.CharField(blank=True, max_length=100)),
                ("route_site", models.CharField(blank=True, max_length=50)),
                ("administered_by", models.CharField(blank=True, max_length=200)),
                (
                    "child_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="immunisation.childimmunisationrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-administration_date"],
            },
        ),
        migrations.CreateModel(
            name="CWCSessionAttendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("doses_given", models.JSONField(default=list)),
                ("growth_recorded", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cwc_attendance",
                        to="clients.person",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="immunisation.cwcsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "child")},
            },
        ),
    ]
